# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Creative Cooking Club' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Cookbook
  pod 'DropDown'
  pod 'Firebase/Core', :inhibit_warnings => true
  pod 'Firebase/Database', :inhibit_warnings => true
  pod 'Firebase/Auth', :inhibit_warnings => true
  # [START base_dependencies]
  pod 'Firebase/Analytics'
  pod 'Firebase/MLVision'
  # [END base_dependencies]
  pod 'Firebase/MLVisionAutoML'
  pod 'Firebase/MLVisionObjectDetection'
  pod 'Firebase/MLVisionBarcodeModel'
  pod 'Firebase/MLVisionFaceModel'
  pod 'Firebase/MLVisionLabelModel'
  pod 'Firebase/MLVisionTextModel'
  
end
